### ISSUE TITLE
SC: 555 Timers

### ISSUE THREAD

**Issue by JTWWilson** [JTWWilson/resources#96]
The 555 Timer markdown page is mainly just copy-and-pasted from [the BourneToInvent page](https://bournetoinvent.com/projects/gcse_theory/4.html). It provides no additional content and ought to be improved.

**Comment by stanley-godfrey** [comment]
Not naming any names of course 😆... Could you do some sort of outline of what you want in there

**Comment by JTWWilson** [comment]
Closing old GCSE content
